"""initial migration

Revision ID: cc24379fc742
Revises: 
Create Date: 2026-09-12 16:27:19.021387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc24379fc742'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_sales', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('food_used', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.CheckConstraint('food_used >= 0', name='valid_food_used'),
    sa.CheckConstraint('total_sales >= 0', name='valid_total_sales'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_logs_date'), ['date'], unique=True)

    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint("category IN ('food', 'supplies')", name='valid_category'),
    sa.CheckConstraint("unit IN ('single', 'pack', 'pounds', 'ounces', 'Gallons')", name='valid_unit'),
    sa.CheckConstraint('amount > 0', name='valid_amount'),
    sa.CheckConstraint('price >= 0', name='valid_price'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchases_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchases_date'))

    op.drop_table('purchases')
    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_logs_date'))

    op.drop_table('daily_logs')
    # ### end Alembic commands ###
